### PR TITLE
Housekeeping

### PR DESCRIPTION
**Pull request by dominykas**
Updating according to latest discussions and docs:

- https://github.com/nodejs/package-maintenance/blob/master/Governance.md
- https://github.com/nodejs/package-maintenance/issues/368
- https://github.com/nodejs/package-maintenance/issues/348

---

- [x] LICENCE.md from the list approved by the OpenJS Foundation
- [x] CODE_OF_CONDUCT.md referencing the Node.js Code of conduct in the admin repo.
- [x] CONTRIBUTING.md which includes the current version of the Developer Certificate of Origin (DCO) used by the Node.js Project
- [x] An PR template(s) used for all Pull requests which includes the current version of the DCO used by the Node.js Project.
    - via https://github.com/pkgjs/.github/blob/master/.github/PULL_REQUEST_TEMPLATE.md
- [x] A README.md which includes references to the GOVERNANCE.md in the package-maintenance repository as the authoritative governance which applies to the repository.

### CODE REVIEW

**Comment by dominykas** [comment]
While we don't explicitly specify that CoC and Contributing docs need to be at the root, I think it definitely makes sense for the CoC to be there - otherwise it's just a teeeeny link in a popup when you're trying to open an issue/PR.

**Comment by dominykas** [comment]
> the license change would need to be approved by him.

There is no license change - the `LICENSE` file has the correct license, it was just the `package.json` which did not get updated: https://github.com/pkgjs/meet/pull/7#discussion_r412148706

That said - yes - we should wait for Wes to approve regardless.

**Comment by wesleytodd** [comment]
I did not intend to be the only one with commit, so let me just fix that right now by adding yall.  After that, I will no longer be blocking progress on accident. :)

**Comment by wesleytodd** [comment]
Hm, I added @dominykas to the collaborators group, but @bnb you were already there with the `maintain` role. That is only below owner, which I can give you all but it should allow commit access as it is, right?

**Comment by wesleytodd** [comment]
Also, for the github sponsor thing, you can remove that as well.  Either that, or you should all add yourselvs.  We don't have a guidance on this yet, and my project scaffold just had that in it since before I moved this into `@pkgjs`.  TBQH I think we should all add our GH sponsors links because we all are doing great work and should be able to get some pay for it, but I will defer to the groups decision on this.

**Pull request merged**
